# Blueprint spec version
version: "1"

services:
  # Layanan Web untuk Aplikasi Laravel
  - name: speedbox-web
    type: web
    env: php
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: speedbox-web
          property: url
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: speedbox-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: speedbox-redis
          property: connectionString
    buildCommand: |
      # 1. Hapus cache lama
      php artisan optimize:clear

      # 2. Instal dependensi PHP
      composer install --no-dev --no-progress

      # 3. Instal dependensi & build aset Frontend (CSS/JS)
      npm install
      npm run build

      # 4. Migrasi database & optimasi Laravel
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

  # Layanan Database PostgreSQL
  - name: speedbox-db
    type: psql
    plan: free
    databaseName: speedbox_db
    user: speedbox_user

  # Layanan Redis
  - name: speedbox-redis
    type: redis
    plan: free
