# Blueprint spec version
version: "1"

services:
  # Layanan Web untuk Aplikasi Laravel
  - name: speedbox-web
    type: web
    env: php
    plan: free
    # PENTING: Tentukan direktori publik Laravel
    rootDir: public
    healthCheckPath: /
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: speedbox-web
          property: url
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: speedbox-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: speedbox-redis
          property: connectionString
    buildCommand: |
      # Perintah build yang lebih kuat dan bersih
      composer install --optimize-autoloader --no-dev --no-progress
      npm install
      npm run build
      php artisan migrate --force
      php artisan optimize
    # PENTING: Hapus startCommand agar Render menggunakan web server bawaannya

  # Layanan Database PostgreSQL
  - name: speedbox-db
    type: database
    plan: free
    databaseName: speedbox_db
    user: speedbox_user

  # Layanan Redis
  - name: speedbox-redis
    type: redis
    plan: free
