services:
  - name: speedbox-web
    type: web
    env: php
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: speedbox-web
          property: url
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: speedbox-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: speedbox-redis
          property: connectionString
    buildCommand: |
      composer install --no-dev
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
  - name: speedbox-db
    type: psql
    plan: free
    databaseName: speedbox_db
    user: speedbox_user
  - name: speedbox-redis
    type: redis
    plan: free
