services:
  # 1. Layanan Web untuk Aplikasi Laravel
  - type: web
    name: speedbox-web
    runtime: php
    plan: free
    rootDir: public
    healthCheckPath: /
    buildCommand: |
      composer install --optimize-autoloader --no-dev --no-progress
      npm install
      npm run build
      php artisan migrate --force
      php artisan optimize
    envVars:
      - key: APP_KEY
        generateValue: true # Render akan otomatis membuat APP_KEY yang aman
      - key: APP_URL
        fromService:
          type: web
          name: speedbox-web
          property: url
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: speedbox-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue # PERBAIKAN: Tipe layanan Redis yang benar
          name: speedbox-redis
          property: connectionString

  # 2. Layanan Redis (didefinisikan sebagai tipe 'keyvalue')
  - type: keyvalue
    name: speedbox-redis
    plan: free
    ipAllowList: [] # Membatasi akses hanya dari dalam Render

# Bagian KHUSUS untuk Database
databases:
  - name: speedbox-db
    databaseName: speedbox_db
    user: speedbox_user
    plan: free
