# Blueprint spec version
version: "1"

# Definisi semua layanan
services:
  # 1. Layanan Web untuk Aplikasi Laravel
  - name: speedbox-web
    type: web
    env: php
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: speedbox-web
          property: url
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: speedbox-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: speedbox-redis
          property: connectionString
    buildCommand: |
      php artisan optimize:clear
      composer install --no-dev
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

  # 2. Layanan Database PostgreSQL
  - name: speedbox-db
    type: postgres
    plan: free
    databaseName: speedbox_db
    user: speedbox_user

  # 3. Layanan Redis
  - name: speedbox-redis
    type: redis
    plan: free
