services:
  # 1. Layanan Web untuk Aplikasi Laravel
  - type: web
    name: speedbox-web
    env: php
    plan: free # Menggunakan paket gratis
    buildCommand: |
      composer install --optimize-autoloader --no-dev --no-progress
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_URL
        value: https://speedbox.com # Ganti dengan URL Anda nanti
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql # Kita akan pakai PostgreSQL
      - key: DATABASE_URL
        fromDatabase:
          name: speedbox-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: speedbox-redis
          property: connectionString

  # 2. Database PostgreSQL
  - type: psql
    name: speedbox-db
    plan: free # Menggunakan paket gratis
    databaseName: speedbox_db
    user: speedbox_user

  # 3. Layanan Redis (untuk Cache/Queue)
  - type: redis
    name: speedbox-redis
    plan: free # Menggunakan paket gratis
