services:
  # Layanan Web yang dibangun dari Dockerfile
  - type: web
    name: speedbox-web
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: speedbox-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: speedbox-redis
          property: connectionString
    # Perintah migrate sekarang dijalankan sebagai pre-deploy command
    preDeployCommand: "php artisan migrate --force"

  # Layanan Redis
  - type: keyvalue
    name: speedbox-redis
    plan: free
    ipAllowList: []

databases:
  # Database PostgreSQL
  - name: speedbox-db
    databaseName: speedbox_db
    user: speedbox_user
    plan: free
